using System.Collections.ObjectModel;
using System.Text.Json;
using Alice.Actors;
using Alice.Commitments;
using Alice.Interaction;
using Alice.Items;
using Alice.Npc;
using Alice.World;
namespace Alice.ModelRuntime;
public sealed record RemotePlannerToolCall(string Name,string? ArgumentsJson);
public sealed class RemotePlannerPlanProposal { private readonly ReadOnlyCollection<RemotePlannerPlanStepProposal> _steps; public RemotePlannerPlanProposal(GoalObjective goalObjective,IEnumerable<RemotePlannerPlanStepProposal> steps){ArgumentNullException.ThrowIfNull(goalObjective);var a=steps?.ToArray()??throw new ArgumentNullException(nameof(steps));if(a.Length==0)throw new ArgumentException("Plan requires steps.",nameof(steps));GoalObjective=goalObjective;_steps=Array.AsReadOnly(a);} public GoalObjective GoalObjective{get;} public IReadOnlyList<RemotePlannerPlanStepProposal> Steps=>_steps; }
public sealed class RemotePlannerPlanlessPlanProposal { private readonly ReadOnlyCollection<RemotePlannerPlanStepProposal> _steps; public RemotePlannerPlanlessPlanProposal(GoalId goalId,IEnumerable<RemotePlannerPlanStepProposal> steps){ArgumentNullException.ThrowIfNull(goalId);var a=steps?.ToArray()??throw new ArgumentNullException(nameof(steps));if(a.Length==0)throw new ArgumentException("Plan requires steps.",nameof(steps));if(a.Any(step=>step is null))throw new ArgumentException("Plan steps must be non-null.",nameof(steps));GoalId=goalId;_steps=Array.AsReadOnly(a);} public GoalId GoalId{get;} public IReadOnlyList<RemotePlannerPlanStepProposal> Steps=>_steps; }
public sealed record RemotePlannerPlanStepProposal(GoalObjective Objective,TargetRef? Target,ResultPredicate DesiredResult);
public abstract record RemotePlannerDecision { private protected RemotePlannerDecision(){} }
public sealed record RemotePlannerCreatePlan(RemotePlannerPlanProposal Proposal):RemotePlannerDecision;
public sealed record RemotePlannerPlanlessCreatePlan(RemotePlannerPlanlessPlanProposal Proposal):RemotePlannerDecision;
public sealed record RemotePlannerRevisePlan(RemotePlannerPlanProposal Proposal):RemotePlannerDecision;
public sealed record RemotePlannerVerify():RemotePlannerDecision;
public sealed record RemotePlannerDefer(string Reason):RemotePlannerDecision;
public sealed record RemotePlannerCancel(string Reason):RemotePlannerDecision;
public enum RemoteInviteResponseKind { Accept, Decline, Clarify, CounterOffer }
public sealed record RemotePlannerInviteResponse(RemoteInviteResponseKind ResponseKind):RemotePlannerDecision;
public sealed record RemotePlannerSelectProposal(string ProposalId):RemotePlannerDecision;
public enum RemoteDialogueReplyKind { Ask, Inform, Clarify, Request, Offer, Recommend, Accept, Decline, CounterOffer, Warn, Apologize, Thank, Complain, Tease, Comfort, Congratulate, CasualComment, ShareNews, ShareGossip }
public enum RemoteDialogueSocialEffectKind { Neutral, Support, Harm, Promise, Breach, Threat, Apology, SharedInterest }
public sealed record RemotePlannerDialogueResponse(RemoteDialogueReplyKind ReplyKind,string ReplyText,RemoteDialogueSocialEffectKind IncomingEffect,RemoteDialogueSocialEffectKind ReplyEffect,double Intensity):RemotePlannerDecision;
public enum RemotePlannerFailureKind { InvocationFailed, InvalidCallCount, UnknownTool, InvalidArguments }
public sealed record RemotePlannerFailure(RemotePlannerFailureKind Kind):RemotePlannerDecision;
public static class RemotePlannerDecisionDecoder
{
 public static RemotePlannerDecision Decode(RemotePlannerRequest request,IEnumerable<RemotePlannerToolCall>? calls){if(calls is null)return new RemotePlannerFailure(RemotePlannerFailureKind.InvalidCallCount);var a=calls.ToArray();if(a.Length!=1)return new RemotePlannerFailure(RemotePlannerFailureKind.InvalidCallCount);var call=a[0];if(call is null||call.ArgumentsJson is null)return new RemotePlannerFailure(RemotePlannerFailureKind.InvalidArguments);try{using var d=JsonDocument.Parse(call.ArgumentsJson,new JsonDocumentOptions{AllowTrailingCommas=false,CommentHandling=JsonCommentHandling.Disallow});var root=d.RootElement;if(root.ValueKind!=JsonValueKind.Object)return Bad();if(request.Binding.Kind==RemotePlannerRequestKind.TownDialogue)return call.Name=="respond_to_dialogue"?ParseTownDialogue(root):new RemotePlannerFailure(RemotePlannerFailureKind.UnknownTool);if(request.Binding.Kind==RemotePlannerRequestKind.TownProposal)return call.Name=="select_proposal"?ParseTownProposal(root,request.Binding.TownProposalBinding):new RemotePlannerFailure(RemotePlannerFailureKind.UnknownTool);if(request.Binding.Kind==RemotePlannerRequestKind.InviteResponse)return call.Name=="respond_to_invite"?ParseInviteResponse(root):new RemotePlannerFailure(RemotePlannerFailureKind.UnknownTool);if(request.Binding.Kind==RemotePlannerRequestKind.PlanlessStrategic)return call.Name switch{"create_plan"=>new RemotePlannerPlanlessCreatePlan(ParsePlanlessPlan(root,request.Binding.ActorId)),"verify"=>Verify(root),"defer"=>new RemotePlannerDefer(ParseReason(root)),_=>new RemotePlannerFailure(RemotePlannerFailureKind.UnknownTool)};return call.Name switch{"create_plan"=>new RemotePlannerCreatePlan(ParsePlan(root,request.Binding.ActorId)),"revise_plan"=>new RemotePlannerRevisePlan(ParsePlan(root,request.Binding.ActorId)),"verify"=>Verify(root),"defer"=>new RemotePlannerDefer(ParseReason(root)),"cancel"=>new RemotePlannerCancel(ParseReason(root)),_=>new RemotePlannerFailure(RemotePlannerFailureKind.UnknownTool)};}catch(JsonException){return Bad();}catch(ArgumentException){return Bad();}catch(InvalidOperationException){return Bad();}}
 private static RemotePlannerDecision ParseTownDialogue(JsonElement root){Exact(root,"reply_kind","reply_text","incoming_effect","reply_effect","intensity");string reply=StringValue(root.GetProperty("reply_kind"));string text=StringValue(root.GetProperty("reply_text"));if(text.Length>600)throw new ArgumentException();JsonElement intensityElement=root.GetProperty("intensity");if(!intensityElement.TryGetDouble(out double intensity)||!double.IsFinite(intensity)||intensity<0||intensity>1)throw new ArgumentException();RemoteDialogueReplyKind replyKind=reply switch{"ask"=>RemoteDialogueReplyKind.Ask,"inform"=>RemoteDialogueReplyKind.Inform,"clarify"=>RemoteDialogueReplyKind.Clarify,"request"=>RemoteDialogueReplyKind.Request,"offer"=>RemoteDialogueReplyKind.Offer,"recommend"=>RemoteDialogueReplyKind.Recommend,"accept"=>RemoteDialogueReplyKind.Accept,"decline"=>RemoteDialogueReplyKind.Decline,"counter_offer"=>RemoteDialogueReplyKind.CounterOffer,"warn"=>RemoteDialogueReplyKind.Warn,"apologize"=>RemoteDialogueReplyKind.Apologize,"thank"=>RemoteDialogueReplyKind.Thank,"complain"=>RemoteDialogueReplyKind.Complain,"tease"=>RemoteDialogueReplyKind.Tease,"comfort"=>RemoteDialogueReplyKind.Comfort,"congratulate"=>RemoteDialogueReplyKind.Congratulate,"casual_comment"=>RemoteDialogueReplyKind.CasualComment,"share_news"=>RemoteDialogueReplyKind.ShareNews,"share_gossip"=>RemoteDialogueReplyKind.ShareGossip,_=>throw new ArgumentException()};return new RemotePlannerDialogueResponse(replyKind,text,ParseSocialEffect(StringValue(root.GetProperty("incoming_effect"))),ParseSocialEffect(StringValue(root.GetProperty("reply_effect"))),intensity);}
 private static RemoteDialogueSocialEffectKind ParseSocialEffect(string effect)=>effect switch{"neutral"=>RemoteDialogueSocialEffectKind.Neutral,"support"=>RemoteDialogueSocialEffectKind.Support,"harm"=>RemoteDialogueSocialEffectKind.Harm,"promise"=>RemoteDialogueSocialEffectKind.Promise,"breach"=>RemoteDialogueSocialEffectKind.Breach,"threat"=>RemoteDialogueSocialEffectKind.Threat,"apology"=>RemoteDialogueSocialEffectKind.Apology,"shared_interest"=>RemoteDialogueSocialEffectKind.SharedInterest,_=>throw new ArgumentException()};
 private static RemotePlannerDecision ParseTownProposal(JsonElement root,RemoteTownProposalRequestBinding binding){Exact(root,"proposal_id");string id=StringValue(root.GetProperty("proposal_id"));return binding.AllowedProposalIds.Contains(id,StringComparer.Ordinal)?new RemotePlannerSelectProposal(id):Bad();}
 private static RemotePlannerDecision ParseInviteResponse(JsonElement root){Exact(root,"response_kind");string token=StringValue(root.GetProperty("response_kind"));return token switch{"accept"=>new RemotePlannerInviteResponse(RemoteInviteResponseKind.Accept),"decline"=>new RemotePlannerInviteResponse(RemoteInviteResponseKind.Decline),"clarify"=>new RemotePlannerInviteResponse(RemoteInviteResponseKind.Clarify),"counter_offer"=>new RemotePlannerInviteResponse(RemoteInviteResponseKind.CounterOffer),_=>Bad()};}
 private static RemotePlannerDecision Bad()=>new RemotePlannerFailure(RemotePlannerFailureKind.InvalidArguments);
 private static RemotePlannerDecision Verify(JsonElement r){Exact(r);return new RemotePlannerVerify();}
 private static string ParseReason(JsonElement r){Exact(r,"reason");var s=r.GetProperty("reason");if(s.ValueKind!=JsonValueKind.String||string.IsNullOrWhiteSpace(s.GetString()))throw new ArgumentException();return s.GetString()!;}
 private static RemotePlannerPlanProposal ParsePlan(JsonElement r,ActorId actor){Exact(r,"goal_objective","steps");return new RemotePlannerPlanProposal(Objective(r.GetProperty("goal_objective")),ParseSteps(r.GetProperty("steps"),actor,false));}
 private static RemotePlannerPlanlessPlanProposal ParsePlanlessPlan(JsonElement r,ActorId actor){Exact(r,"goal_id","steps");return new RemotePlannerPlanlessPlanProposal(new GoalId(StringValue(r.GetProperty("goal_id"))),ParseSteps(r.GetProperty("steps"),actor,true));}
 private static IReadOnlyList<RemotePlannerPlanStepProposal> ParseSteps(JsonElement steps,ActorId actor,bool planless){if(steps.ValueKind!=JsonValueKind.Array||steps.GetArrayLength()==0)throw new ArgumentException();var list=new List<RemotePlannerPlanStepProposal>();foreach(var s in steps.EnumerateArray()){if(s.ValueKind!=JsonValueKind.Object)throw new ArgumentException();bool hasTarget=s.TryGetProperty("target_ref",out JsonElement targetElement);Exact(s,hasTarget?["objective","target_ref","desired_result"]:["objective","desired_result"]);var o=planless?PlanlessObjective(s.GetProperty("objective")):Objective(s.GetProperty("objective"));TargetRef? target=hasTarget?new TargetRef(StringValue(targetElement)):null;var result=Result(s.GetProperty("desired_result"),actor);if((result is InteractionTargetReached x&&target!=x.TargetRef)||(result is TargetTerminal y&&target!=y.TargetRef)||(result is InventoryAtLeast or BodyStateWithin or CommitmentStatusMatches or ExperienceCompleted)&&target is not null)throw new ArgumentException();if(o is ReachTargetObjective reach&&target!=reach.TargetRef)throw new ArgumentException();if(!Pair(o,result))throw new ArgumentException();list.Add(new(o,target,result));}return list;}
 private static GoalObjective Objective(JsonElement e){var kind=Kind(e);return kind switch{"acquire_item"=>Acquire(e),"maintain_body"=>Maintain(e),_=>throw new ArgumentException()};}
 private static GoalObjective PlanlessObjective(JsonElement e){var kind=Kind(e);return kind switch{"acquire_item"=>Acquire(e),"maintain_body"=>Maintain(e),"reach_target"=>Reach(e),"fulfill_commitment"=>Fulfill(e),"experience"=>Experience(e),_=>throw new ArgumentException()};}
 private static GoalObjective Acquire(JsonElement e){Exact(e,"kind","item_type_id","quantity");return new AcquireItemObjective(new ItemTypeId(StringValue(e.GetProperty("item_type_id"))),Positive(e.GetProperty("quantity")));}
 private static GoalObjective Maintain(JsonElement e){Exact(e,"kind","metric","minimum_acceptable_level");return new MaintainBodyObjective(Metric(StringValue(e.GetProperty("metric"))),Fifty(e.GetProperty("minimum_acceptable_level")));}
 private static GoalObjective Reach(JsonElement e){Exact(e,"kind","target_ref");return new ReachTargetObjective(new TargetRef(StringValue(e.GetProperty("target_ref"))));}
 private static GoalObjective Fulfill(JsonElement e){Exact(e,"kind","commitment_id");return new FulfillCommitmentObjective(new CommitmentId(StringValue(e.GetProperty("commitment_id"))));}
 private static GoalObjective Experience(JsonElement e){Exact(e,"kind","experience_id");return new ExperienceObjective(new ExperienceId(StringValue(e.GetProperty("experience_id"))));}
 private static ResultPredicate Result(JsonElement e,ActorId a){var kind=Kind(e);return kind switch{"inventory_at_least"=>Inventory(e,a),"body_state_within"=>Body(e,a),"interaction_target_reached"=>Reached(e,a),"target_terminal"=>Terminal(e,a),"commitment_status_matches"=>Commitment(e,a),"experience_completed"=>ExperienceResult(e,a),_=>throw new ArgumentException()};}
 private static ResultPredicate Inventory(JsonElement e,ActorId a){Exact(e,"kind","item_type_id","quantity");return new InventoryAtLeast(a,new ItemTypeId(StringValue(e.GetProperty("item_type_id"))),Positive(e.GetProperty("quantity")));}
 private static ResultPredicate Body(JsonElement e,ActorId a){Exact(e,"kind","metric","minimum_acceptable_level");return new BodyStateWithin(a,Metric(StringValue(e.GetProperty("metric"))),Fifty(e.GetProperty("minimum_acceptable_level")));}
 private static ResultPredicate Reached(JsonElement e,ActorId a){Exact(e,"kind","target_ref","interaction_range");return new InteractionTargetReached(a,new TargetRef(StringValue(e.GetProperty("target_ref"))),new InteractionRange(NonNegative(e.GetProperty("interaction_range"))));}
 private static ResultPredicate Terminal(JsonElement e,ActorId a){Exact(e,"kind","target_ref");return new TargetTerminal(a,new TargetRef(StringValue(e.GetProperty("target_ref"))));}
 private static ResultPredicate Commitment(JsonElement e,ActorId a){Exact(e,"kind","commitment_id","status");if(StringValue(e.GetProperty("status"))!="fulfilled")throw new ArgumentException();return new CommitmentStatusMatches(a,new CommitmentId(StringValue(e.GetProperty("commitment_id"))),CommitmentStatus.Fulfilled);}
 private static ResultPredicate ExperienceResult(JsonElement e,ActorId a){Exact(e,"kind","experience_id");return new ExperienceCompleted(a,new ExperienceId(StringValue(e.GetProperty("experience_id"))));}
 private static string Kind(JsonElement e){if(e.ValueKind!=JsonValueKind.Object)throw new ArgumentException();var k=e.GetProperty("kind");if(k.ValueKind!=JsonValueKind.String)throw new ArgumentException();return k.GetString()!;} private static string StringValue(JsonElement e){if(e.ValueKind!=JsonValueKind.String||string.IsNullOrWhiteSpace(e.GetString()))throw new ArgumentException();return e.GetString()!;} private static int Positive(JsonElement e){if(!e.TryGetInt32(out var v)||v<=0)throw new ArgumentException();return v;} private static int Fifty(JsonElement e){if(!e.TryGetInt32(out var v)||v!=50)throw new ArgumentException();return v;} private static double NonNegative(JsonElement e){if(!e.TryGetDouble(out var v)||!double.IsFinite(v)||v<0)throw new ArgumentException();return v;} private static BodyMetric Metric(string s)=>s switch{"health"=>BodyMetric.Health,"satiety"=>BodyMetric.Satiety,"spirit"=>BodyMetric.Spirit,_=>throw new ArgumentException()}; private static bool Pair(GoalObjective o,ResultPredicate r)=>(o is AcquireItemObjective a&&r is InventoryAtLeast i&&a.ItemTypeId==i.ItemTypeId&&a.Quantity==i.Quantity)||(o is AcquireItemObjective&&r is InteractionTargetReached or TargetTerminal)||(o is MaintainBodyObjective m&&r is BodyStateWithin b&&m.Metric==b.Metric&&m.MinimumAcceptableLevel==b.MinimumAcceptableLevel)||(o is ReachTargetObjective reach&&r is InteractionTargetReached reached&&reach.TargetRef==reached.TargetRef)||(o is FulfillCommitmentObjective fulfill&&r is CommitmentStatusMatches commitment&&fulfill.CommitmentId==commitment.CommitmentId&&commitment.Status==CommitmentStatus.Fulfilled)||(o is ExperienceObjective experience&&r is ExperienceCompleted completed&&experience.ExperienceId==completed.ExperienceId);
 private static void Exact(JsonElement e,params string[] names){var seen=new HashSet<string>(StringComparer.Ordinal);foreach(var p in e.EnumerateObject())if(!seen.Add(p.Name)||!names.Contains(p.Name,StringComparer.Ordinal))throw new ArgumentException();if(seen.Count!=names.Length)throw new ArgumentException();}
}
